### ISSUE TITLE
fix mobile view for landing page

### ISSUE THREAD

**Issue by clhenrick** [aepyornis/BushwickCommunityMap#6]
Title bar gets cut off in mobile portrait view. Believe I fixed this and it just needs to get updated on the website's server.
![screen shot 2015-05-21 at 12 33 16 pm](https://cloud.githubusercontent.com/assets/161748/7753779/adb20de2-ffb5-11e4-891d-c51c9e1762d7.png)
![screen shot 2015-05-21 at 12 33 06 pm](https://cloud.githubusercontent.com/assets/161748/7753782/b01e07fc-ffb5-11e4-8db3-f7d5b169842c.png)

**Comment by aepyornis** [comment]
done :)
